spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.76.136:3306/gulimall_oms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 192.168.76.136
    port: 5672
    #  开启发送端确认
    publisher-confirms: true
    # 开启消息抵达队列确认
    publisher-returns: true
    #只要抵达队列，以异步方式优先回调publisher-returns
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    sentinel:
      transport:
        dashboard: 192.168.76.136:8333

  application:
    name: gulimall-order


  session:
    store-type: redis

  redis:
    host: 192.168.76.136
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  zipkin:
    base-url: http://192.168.76.136:9411/
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1

gulimall:
  thread:
    core-size: 20
    max-size: 20
    keep-alive-time: 200



mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: 9000
  servlet:
    session:
      timeout: 30m
management:
  endpoints:
    web:
      exposure:
        include: '*'



